version: '3'
services:
  strapi-backend:
    build: .
    ports:
      - '1337:1337'
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db.wmblmwgaoxuriklbiezz.supabase.co
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=c0nstInfinty
      - DATABASE_SSL=true
    depends_on:
      - strapi-backend
