services:
  db:
    image: postgres
    container_name: ecommerce-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    image: jackdev21/ecommerce-backend:latest
    container_name: ecommerce-backend
    depends_on:
      - db
    ports:
      - "1337:1337"
    environment:
      HOST: 0.0.0.0
      PORT: 1337
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_SSL: "false"
      APP_KEYS: "k6ZuxvEKmSjrPGLrpqMlIA==,3C456QnJ01csSsp+JvEWaw==,l+RYXn0pbOHp8U+Onkifnw==,pBtFJxJ3rHT/iYvCVeX1wA=="
      API_TOKEN_SALT: "Vg/NvdNPnmIl0KMXHVYD2g=="
      ADMIN_JWT_SECRET: "g5TfBxviQ1L3vAE3M83LTg=="
      TRANSFER_TOKEN_SALT: "PkqLgNCPfzbCpB7WsEn7BA=="
      JWT_SECRET: "60/2GpceNocidcESm/0RbQ=="
      CLOUDINARY_NAME: "dwsrlq6vq"
      CLOUDINARY_KEY: "214474931182264"
      CLOUDINARY_SECRET: "ZHfpmDFZSDhOk1hzfnFgsze_Ocg"
      RESEND_API_KEY: "re_iTGwfxLo_3MhdZDM2FAQdcLnM9wAmf47j"
      STRIPE_SECRET_KEY: "sk_test_51QmJ9fP2e90YVnJDPszSdnzZWozuRdzbhX4IQ8jH0BLSqlpvC6VX76OVQhZzRomkLWG6l3BiD3RdcQcjZ8apg5K700ehZu1JUf"
